config/routes.rb
Rails.application.routes.draw do
  
  match "/auth/:provider/callback", to: "sessions#create", via: :get
  match "/login" => "sessions#new", as: :login, via: :get
  match "/login-facebook" => redirect("/auth/facebook"), as: :facebookLogin, via: :get
  match "/login-twitter" => redirect("/auth/twitter"), as: :twitterLogin, via: :get
  match "/logout" => "sessions#destroy", as: :logout, via: :get

  resources :products do
    member do
      get :delete
    end
  end

  resources :addresses
  
  resources :orders do 
  	member do
  		get :confirm, as: :confirm 
  	end
  end
  
  resources :order_items

  root "products#index"

end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items, dependent: :destroy
	belongs_to :user, optional: true
	belongs_to :address, optional: true

	validates :order_items, presence: { on: :update, message: " - Oops your cart is empty!" }
	validates :address, presence: { on: :update, message: " - Where do you want us to send your veggies?" }
	validates_associated :order_items, on: :update, message: "We don't have enough:"

	def total
		self.order_items.sum { |item| item.subtotal }
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  #before_action :check_stock, only: [:update]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where(user_id: session[:user_id]).where(status: "submitted").all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    if @order.update(order_params.merge(status: 'submitted'))
      @order.order_items.each do |item|
        item.remove_stock          
      end
      session[:order_id] = nil
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully emptied.' }
      format.json { head :no_content }
    end
  end

  def confirm
    if session[:user_id] == nil
      render 'sessions/new' 
    else
      @order = Order.find(params[:id])
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {}).permit(:user_id, :status, :address_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_confirm.html.erb
<div class="container">
<%= form_for @order, remote: true do |f| %>
<div class="modal-content order-summary">
	<div class="modal-header">
		<h1>Your Order</h1>
	</div>

	<div class="modal-body order-detail">
		<div class="container">
		
		<div class="col-md-6">
			<table class="order-header">
				<ul class="errors"></ul> 
				<h4>Your Details</h4>
				<tr>
					<th>Customer: </th>
					<td><%= @order.user.name %></td>
				</tr>
				<tr>
					<th>Order Status: </th>
					<td><%= @order.status %></td>
				</tr>
			</table>
			<hr>
			<h4>Shipping</h4>
			<table>
				<tr>
					<th>Ship to: </th>
					<td>
						<%= f.select :address_id, current_user.addresses.collect{ |a| [a.to_s, a.id] }, {}, { class:"form-control" } %>
					</td>
					<td><%= link_to "New Address", new_address_path, remote: true %></td>
				</tr>
			</table>
		</div>


		<div class="col-md-6">		
			<h4>Items</h4>
			<table class="item-summary">
				<tr>
					<th></th>
					<th></th>
					<th>Quantity</th>
					<th>Unit Price</th>
					<th>Subtotal</th>
				</tr>
				<% row = 0 %>
				<% @order.order_items.each do |item| %>	
				<tr class="item-row">
					<td><%= row = row + 1 %></td>
					<td><%= image_tag "products/#{item.product.image_url}", class: "mini-pic" %><%= item.product.title %></td>
					<td><%= item.quantity %></td>
					<td><%= print_price item.product.price %></td>
					<td><%= print_price item.subtotal %></td>
				</tr>
				<% end %>

				<!-- I was going to put in an extra line item for shipping

					<tr class="item-row">
						<td><%=row = row + 1 %></td>
						<td>Shipping</td>
						<td colspan="2"></td>
						<td>$20.00</td>
					</tr>
				-->

				<tr class="total-row">		
					<td colspan="3"></td>
					<td>Total:</td>
					<td><%= print_price @order.total %></td>
				</tr>
			</table>
		</div>
		</div>
	</div>

	<div class="modal-footer">
		<%= link_to 'Back', root_path, class: "btn btn-outline-success" %>
		<%= f.submit "Send Order", class: "btn btn-outline-success" %>
	</div>
</div>
<% end %>
</div>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_order_items.html.erb
<tr>
	<td><%= item.product.title %></td>
	<td><%= link_to item.quantity, edit_order_item_path(item) %></td>
	<td><%= print_price item.product.price %></td>
	<td><%= print_price item.subtotal %></td>
	<td><%= print_stock item.product.stock, item.quantity %></td>
	<td><%= link_to 'Delete', item, method: :delete, data: {confirm: "Are You sure"} %></td>
</tr>

app/views/orders/confirm.js.erb
$("#page-content").html("<%= j render 'confirm' %>")

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="container">
<div class="modal-content order-summary">
  <div class="modal-header">
    <h1>Your Orders</h1>
  </div>

  <div class="modal-body order-detail">
    <div class="container">
    
    <div class="col-md-6">
    <% if @orders.any? %>
    <table class="order-header">
    <% @orders.each_with_index do |order, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= print_price(order.total) %></td>
        <td><%= order.updated_at.strftime("%b %d, %Y") %></td>
        <td><%= link_to 'Show', order, class: "btn btn-success"%></td>
      </tr>
    <% end %>
    </table>
    <% else %>
    <p> You haven't made any orders yet </p>
    <% end %>
    </div>
    </div>
    </div>

  <div class="modal-footer">
    <%= link_to 'Back', root_path, class: "btn btn-outline-success" %>
  </div>
</div>
</div>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<div class="container">
<div class="modal-content order-summary">
  <div class="modal-header">
    <h1>Order #<%= @order.id %> </h1>
  </div>

  <div class="modal-body order-detail">
		<div class="container">
		
		<div class="col-md-6">
			<table class="order-header">
				<h4>Your Details</h4>
				<tr>
					<th>Customer: </th>
					<td><%= @order.user.name %></td>
				</tr>
				<tr>
					<th>Order Status: </th>
					<td><%= @order.status %></td>
				</tr>
			</table>
			<hr>
			<h4>Shipping</h4>
			<table>
				<tr>
					<th>Ship to: </th>
					<td><%= @order.address %></td>
				</tr>
			</table>
		</div>


		<div class="col-md-6">		
			<h4>Items</h4>
			<table class="item-summary">
				<tr>
					<th></th>
					<th></th>
					<th>Quantity</th>
					<th>Unit Price</th>
					<th>Subtotal</th>
				</tr>
				<% row = 0 %>
				<% @order.order_items.each do |item| %>	
				<tr class="item-row">
					<td><%= row = row + 1 %></td>
					<td><%= image_tag "products/#{item.product.image_url}", class: "mini-pic" %><%= item.product.title %></td>
					<td><%= item.quantity %></td>
					<td><%= print_price item.product.price %></td>
					<td><%= print_price item.subtotal %></td>
				</tr>
				<% end %>

				<!-- I was going to put in an extra line item for shipping

					<tr class="item-row">
						<td><%=row = row + 1 %></td>
						<td>Shipping</td>
						<td colspan="2"></td>
						<td>$20.00</td>
					</tr>
				-->

				<tr class="total-row">		
					<td colspan="3"></td>
					<td>Total:</td>
					<td><%= print_price @order.total %></td>
				</tr>
			</table>
		</div>
		</div>
	</div>

	<div class="modal-footer">
		<%= link_to 'Back', orders_path, class: "btn btn-outline-success" %>
	</div>
</div>
</div>

app/views/orders/update.js.erb
$("ul.errors").html("")
<% if @order.errors.any? %>
  <% @order.errors.messages.values.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message[0].html_safe %>"))
    <% @order.order_items.each do |item| %>
    	<% if item.errors.any? %>
    		<% item.errors.full_messages.each do |message| %>
    			$("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
    		<% end %>	
    	<% end %>
    <% end %>
  <% end %>
<% else %>
	window.location.assign('<%= j orders_path %>');
<% end %>