config/routes.rb
Rails.application.routes.draw do
  
  match "/auth/:provider/callback", to: "sessions#create", via: :get
  match "/login" => "sessions#new", as: :login, via: :get
  match "/login-facebook" => redirect("/auth/facebook"), as: :facebookLogin, via: :get
  match "/login-twitter" => redirect("/auth/twitter"), as: :twitterLogin, via: :get
  match "/logout" => "sessions#destroy", as: :logout, via: :get

  resources :products do
    member do
      get :delete
    end
  end

  resources :addresses
  
  resources :orders do 
  	member do
  		get :confirm, as: :confirm 
  	end
  end
  
  resources :order_items

  root "products#index"

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	validates :order_id, presence: true
	validates :product_id, presence: true
	validates :quantity, numericality: {only_integer: true, greater_than_or_equal_to: 0}
	validate :check_stock

	belongs_to :order
	belongs_to :product


	def check_stock
		puts self.product.stock
		puts self.quantity
		if self.product.stock < self.quantity
			self.errors[:base] << "- #{self.product.title} (#{self.product.stock} in stock)"
			false
		end
    end

	def subtotal
		self.quantity * self.product.price
	end

	def remove_stock
		product.stock -= self.quantity
		product.save
	end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order_item, only: [:show, :edit, :update, :destroy]
  before_action :load_order, only: [:create, :update]

  # GET /order_items/1/edit
  def edit
  end

  # POST /order_items
  # POST /order_items.json
  def create
    @order_item = OrderItem.find_or_initialize_by(product_id: params[:product_id], order_id: @order.id)
    @order_item.quantity += params[:change].to_i

    if @order_item.quantity  == 0
      @order_item.destroy
    else
      @order_item.save
    end
  end

  # PATCH/PUT /order_items/1
  # PATCH/PUT /order_items/1.json
  def update
    @order_item.quantity = params[:order_item][:quantity].to_i
    if @order_item.quantity == 0
      @order_item.destroy
    else
      @order_item.update(order_item_params)
    end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.json
  def destroy
    @order = @order_item.order
    @order_item.destroy   
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(:product_id, :order_id, :quantity)
    end

end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_form.html.erb
<%= form_for(order_item) do |f| %>
  <% if order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
      <% order_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p><%= order_item.product.title %></p>
  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_items/_out_of_stock.html.erb
<div class="modal-dialog active" role="document">
  <div id="#modal-content" class="modal-content">
	  <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	    <h4 class="modal-title" id="myModalLabel">
	      Out of stock
	    </h4>
	  </div>
	  <div class="modal-body">
	  <td><%= image_tag "products/#{@order_item.product.image_url}", class: "mini-pic" %></td>  
	  <td>Sorry! We don't have enough <%= @order_item.product.title %> (<%= @order_item.product.stock %> in stock)</td>  

	  </div>
	  <div class="modal-footer">
	    <%= link_to "Close", "#", class:"btn btn-outline-success" %> 
	  </div>
   </div>
</div>

app/views/order_items/_save.js.erb
var order_id = "#line-item-<%= @order_item.id %>";
var product_id = "#product-<%= @order_item.product.id %>";

<% if @order_item.errors.any? %>
	$('#product-modal').html("<%= j render 'out_of_stock' %>");
	$('#product-modal').modal('show')
<% else %>

	//Update the total price
	$(".total").html("<%= j render 'products/total' %>");

	if (<%= @order_item.quantity != 0 %>) {
		$(".total").toggleClass('update-item').bind('animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd', function(e){
			$(".total").removeClass('update-item');
		});
	}
	else{
		$(".total").toggleClass('negative-update-item').bind('animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd', function(e){
			$(".total").removeClass('negative-update-item');
		});
	}

	//Update the item in the product list to show correct quantity
	$(product_id + " .add-to-cart").html("<%= j render :partial => 'products/add_to_cart', :locals => {:product => @order_item.product} %>");


	// If a new item
	if ($(order_id)[0] == null) {
		// Append the new item to the bottom of the list with an animation
		$(".item-list").append("<%= j render :partial => 'products/cart_item', :locals => {:item => @order_item} %>");
		$(order_id).toggleClass('new-item')
		$(order_id).toggleClass('add-item').bind('animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd', function(e){
	    	$(order_id).removeClass('add-item new-item');
		}); 
		$(order_id).slideDown(500);
	}
	// Must be an old one
	else {
		// Fade the item out, replace the html and bring it back
		
		if (<%= @order_item.quantity != 0 %>) {

			$(order_id).replaceWith("<%= j render :partial => 'products/cart_item', :locals => {:item => @order_item} %>");
			$(order_id).toggleClass('update-item').bind('animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd', function(e){
		    	$(order_id).removeClass('update-item');
			});
		}
		else {
			$(order_id).slideUp(500);
			$(order_id).toggleClass('negative-update-item').bind('animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd', function(e){
				$(order_id).remove();
			});

		}
	}
<% end %>

app/views/order_items/create.js.erb
<%= render "save" %>

app/views/order_items/destroy.js.erb
var order = $("#line-item-<%= @order_item.id %>");
var product = $("#product-<%= @order_item.product.id %>");

// Update the product partial
product.replaceWith("<%= j render partial: 'products/product', locals: { product: @order_item.product } %>");

//Update the total price
$(".total").html("<%= j render 'products/total' %>");
$(".total").toggleClass('negative-update-item').bind('animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd', function(e){
	$(".total").removeClass('negative-update-item');
});

// Fade the item out of the cart and remove the html
$(order).slideUp(500);
$(order).toggleClass('negative-update-item').bind('animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd', function(e){
	$(order).remove();
});

app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

app/views/order_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Order</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.product_id %></td>
        <td><%= order_item.order_id %></td>
        <td><%= order_item.quantity %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Item', new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @order_item.product_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_item.quantity %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>

app/views/order_items/update.js.erb
<%= render "save" %>