config/routes.rb
Rails.application.routes.draw do
  
  match "/auth/:provider/callback", to: "sessions#create", via: :get
  match "/login" => "sessions#new", as: :login, via: :get
  match "/login-facebook" => redirect("/auth/facebook"), as: :facebookLogin, via: :get
  match "/login-twitter" => redirect("/auth/twitter"), as: :twitterLogin, via: :get
  match "/logout" => "sessions#destroy", as: :logout, via: :get

  resources :products do
    member do
      get :delete
    end
  end

  resources :addresses
  
  resources :orders do 
  	member do
  		get :confirm, as: :confirm 
  	end
  end
  
  resources :order_items

  root "products#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  	 
  	 def load_order
        #session[:order_id] = nil
        @order = Order.find_or_initialize_by(id: session[:order_id], status: "unsubmitted", user_id: session[:user_id])
        if @order.new_record?
          @order.save!
          session[:order_id] = @order.id
        end
    end	

	  def current_user
	    @current_user ||= User.find(session[:user_id]) if session[:user_id]
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed btn-outline-success" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">E-Veggies</a>
    </div>

   <!-- Collect the nav links, forms, and other content for toggling -->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

          <% if current_user %>
		    <li><p class="navbar-text"><%= current_user.name %></p> </span></li>
            <li><%= link_to "Shop", root_path %></li>
         	  <li><%= link_to "Orders", orders_path %></li>
	      	<%= link_to "Logout", logout_path, id: "login", 
	      			class: "navbar-btn btn btn-outline-success" %>				
		  <% else %>
		  	<%= link_to "Login", login_path, id: "login", 
	      			class: "navbar-btn btn btn-outline-success", remote: true %>
		  <% end %>
          
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>