config/routes.rb
Rails.application.routes.draw do
  
  match "/auth/:provider/callback", to: "sessions#create", via: :get
  match "/login" => "sessions#new", as: :login, via: :get
  match "/login-facebook" => redirect("/auth/facebook"), as: :facebookLogin, via: :get
  match "/login-twitter" => redirect("/auth/twitter"), as: :twitterLogin, via: :get
  match "/logout" => "sessions#destroy", as: :logout, via: :get

  resources :products do
    member do
      get :delete
    end
  end

  resources :addresses
  
  resources :orders do 
  	member do
  		get :confirm, as: :confirm 
  	end
  end
  
  resources :order_items

  root "products#index"

end

app/models/product.rb
class Product < ApplicationRecord
	validates :title, :stock, :price, :image_url, presence: true
	validates :price, numericality: {}
	validates :stock, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

	has_many :order_items

	def price=(input)
		input.delete!("$")
		super
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :load_order, only: [:index, :create, :update]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @order = Order.find(session[:order_id])
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @products = Product.all
    @product = Product.create(product_params)
  end

  def update
    @products = Product.all
    @product = Product.find(params[:id])
    @product.update_attributes(product_params)
  end

  def delete
    @product = Product.find(params[:id])
  end

  def destroy
    @products = Product.all
    @product = Product.find(params[:id])
    @order = Order.find(session[:order_id])
    @product.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :description, :image_url, :stock)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

	def print_price(price)
		number_to_currency price
	end

	def print_stock(stock, requested = 1)
	
		if stock < 0
			"Out of stock"
		else
			if stock >= requested
				content_tag(:span, "In stock (#{stock})")
			else
				content_tag(:span, "No Stock! (#{stock})", class: "low-stock")
			end
		end
	end

	def get_order_quantity(product_id, order_id)
		items = Order.find(order_id).order_items
		item = items.find_by(product_id: product_id)

		if item != nil
			item.quantity
		else
			0
		end
	end

end

app/views/products/_add_to_cart.html.erb
<% if @order.order_items.find_by(product_id: product.id) != nil %>
      
  <%= button_to order_items_path(product_id: product.id, change: -1), class:"btn btn-success", remote: true  do %>
    <span><%= icon('minus') %></span>
  <% end %>
  
  <%= form_for(@order.order_items.find_by(product_id: product.id), remote: true) do |f| %>  
    <%= f.text_field :quantity, class:"quantity-field" %>
  <% end %>
  
  <%= button_to order_items_path(product_id: product.id, change: 1), class:"btn btn-success", remote: true  do %>
    <span><%= icon('plus') %></span>
  <% end %>

<% else %>
  <%= button_to "Add to Cart", order_items_path(product_id: product.id, change: 1), class:"btn btn-success", remote: true %>
<% end %>

app/views/products/_cart_item.html.erb
<div class="line-item" id="line-item-<%= item.id %>"> 
	<span><%= link_to item.quantity, edit_order_item_path(item) %></span>
	<span><%= item.product.title %></span>
	<span class="to-end"><%= link_to icon("times"), item, method: :delete, remote: true %></span>
	<span class="to-end"><%= print_price item.subtotal %></span>
</div>

app/views/products/_delete.html.erb
<div class="modal-dialog" role="document">
  <div id="#modal-content" class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">
        Delete Product
      </h4>
    </div>
    <div class="modal-body">
      <ul class="errors"></ul> 
      <p> Are you sure you want to delete <%= @product.title %> from the database? </p>
    </div>
    <div class="modal-footer">
      <%= link_to "No", "#", class: "btn btn-outline-success" %>
      <%= link_to "Yes", product_path(@product), method: :delete, remote: true, class: "btn btn-outline-success" %> 
    </div>
  </div>
</div>

app/views/products/_edit.html.erb
<div class="modal-dialog" role="document">
  <div id="#modal-content" class="modal-content">
    <%= render 'form' %>
  </div>
</div>

app/views/products/_form.html.erb
<%= form_for(@product, remote: true) do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">
      <%= ( f.object.new_record? ? "Create a new product" : "Update product") %>
    </h4>
  </div>
  <div class="modal-body">
    
  <ul class="errors"></ul>  

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control" %>
  </div>

  <div class="field">
    <%= f.label :price, "Price (like 2.99)" %>
    <%= f.text_field :price, value: print_price(@product.price), class:"form-control" %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class:"form-control" %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url, class:"form-control" %>
  </div>

  <div class="field">
    <%= f.label :stock %>
    <%= f.text_field :stock, class:"form-control" %>
  </div>

  </div>
  <div class="modal-footer">
    <%= f.submit class:"btn btn-outline-success" %> 
  </div>
<% end %>

app/views/products/_index.html.erb
<% @products.each do |p| %>
  <%= render partial: 'product', locals: {product: p} %>
<% end %>

app/views/products/_new.html.erb
<div class="modal-dialog" role="document">
  <div id="#modal-content" class="modal-content">
    <%= render 'form' %>
  </div>
</div>

app/views/products/_product.html.erb
<li id="product-<%= product.id%>" class="single-item col-md-3 col-sm-4 col-xs-6">
  <div class="solid-area">
    <div class="admin-tools">
      <div class="justice"><%= link_to icon('wrench'), edit_product_path(product), remote: true %></div>
      <div class="justice"><%= print_stock(product.stock) %></div>
      <div class="justice"><%= link_to icon('trash'), delete_product_path(product), remote: true %></div>
    </div>
    <div class="thumb">
    <%= image_tag("products/#{product.image_url}") %>
    </div>
    <div class="add-to-cart">
      <%= render partial: 'products/add_to_cart', locals: {product: product} %>
    </div>
  </div>
  
  <div class = "product-info">
      <div class = "pull-left">
        <%= product.title %>
        <%= product.unit %>
      </div>
      <div class = "pull-right">
        <%= print_price(product.price) %>
      </div>
  </div>
</li>

app/views/products/_save.js.erb
$("ul.errors").html("")
<% if @product.errors.any? %>
  <% @product.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".product-list").html("<%= j render 'index' %>");
  $("#product-modal").modal("hide")
  <% if @product == nil %>
  	
  <% else %>
  $("#product-<%= @product.id %> .solid-area").addClass("update-item").bind('animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd', function(e){
	$("#product-<%= @product.id %> .solid-area").removeClass('update-item');
  });
  <% end %>
<% end %>

app/views/products/_total.html.erb
<h3>Total: <%= print_price @order.total %><h3>

app/views/products/destroy.js.erb
<%= render 'save' %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/edit.js.erb
$('#product-modal').html("<%= j render 'edit' %>");
$('#product-modal').modal('show')

app/views/products/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>